Feat/back test
snuhcs-course/swpp-2023-project-team-2 pull request #53
Opened 2023-11-15 16:34 UTC by yangchanhk98

# 수정사항

* 회원탈퇴 시 자신이 만든 이모지, 게시글 삭제 & 자신이 save한 이모지의 num_saved 감소 관련 코드 수정
* UserService layer 테스트 전체 구현

2023-11-15 17:10 UTC, thisisWooyeol requested changes

2023-11-15 17:10 UTC, thisisWooyeol commented on springboot/src/main/kotlin/com/goliath/emojihub/springboot/domain/user/controller/UserController.kt
> +        )
@yangchanhk98 코드 전반적으로 `signUpRequest`의 각 필드를 펼쳐서 signUp 및 여러 메소드에 넣어주는 방식으로 수정을 진행하신 것으로 확인됩니다. design pattern 관점에서 각 필드를 풀지 않고 `signUpRequest`라는 객체로 전달하는 것이 범용성 측면에서 좋을 것 같은데, 이렇게 수정하신 이유가 있을까요?

2023-11-15 17:10 UTC, thisisWooyeol commented on springboot/src/test/kotlin/com/goliath/emojihub/springboot/domain/user/service/UserServiceTest.kt
> +internal class UserServiceTest {
![image](https://github.com/snuhcs-course/swpp-2023-project-team-2/assets/97590283/dcce8687-9c4b-4dbd-b548-a0cfb4c52f1a)

test coverage 입니다

2023-11-16 11:34 UTC, yangchanhk98 commented on springboot/src/main/kotlin/com/goliath/emojihub/springboot/domain/user/controller/UserController.kt
> +        )
@thisisWooyeol  controller에서 API call을 위해 request body(signUpRequest)로 파라미터를 받은 것인데, Service까지는 signUpRequest를 그대로 가져가는 것으로 바꿀까요??

2023-11-16 11:40 UTC, yangchanhk98 commented on springboot/src/test/kotlin/com/goliath/emojihub/springboot/domain/user/service/UserServiceTest.kt
> +internal class UserServiceTest {
감사합니다!

2023-11-16 11:41 UTC, yangchanhk98 commented on springboot/src/main/kotlin/com/goliath/emojihub/springboot/domain/user/controller/UserController.kt
> +        )
그럼 우선은 merge해 주시고 나중에 코드 리팩토링 때 다른 user, emoji, post 모두 controller-service 패턴을 동일하게 맞추면서 바꾸도록 할게요!

2023-11-16 12:00 UTC, thisisWooyeol commented on springboot/src/main/kotlin/com/goliath/emojihub/springboot/domain/user/controller/UserController.kt
> +        )
@yangchanhk98 수업시간에 말씀해주신 부분에 대해서 고민을 해봤는데 지금 `UserService` 처럼 파싱된 상태로 
값을 받아서 처리하는게 자연스러운 것 같습니다! comment resolve하고 머지하겠습니다 :+1:

2023-11-16 12:00 UTC, thisisWooyeol approved these changes

2023-11-16 12:00 UTC, merged