Feat/back user api
snuhcs-course/swpp-2023-project-team-2 pull request #6
Opened 2023-10-12 07:33 UTC by yangchanhk98

# 수정사항

* Fixme 에 맞는 코드 수정(created_emojis와 liked_emojis를 Array->MutableList 로 변경)
* 기타 코드 수정(gitignore에 /src/main/resources/serviceAccountKey.json삽입, 기타 코드 간편화)
* signup API 구현
* login API 구현

2023-10-12 07:41 UTC, peng-u-0807 requested changes

2023-10-12 07:41 UTC, peng-u-0807 commented on springboot/src/main/kotlin/com/goliath/emojihub/springboot/dto/UserDto.kt
> +    var liked_emojis: MutableList<String>? = null
위의 필드들은 `User`를 생성할 때 필수적으로 있어야 할 값이라 생각했는데, 혹시 `nullable`인 이유가 있을까요? 없다면 수정해주시는 것이 어떨까 싶습니다

2023-10-12 07:41 UTC, peng-u-0807 commented on springboot/src/main/kotlin/com/goliath/emojihub/springboot/dto/SignUpRequest.kt
> +    var password: String,
[figma](https://www.figma.com/file/hR0qkDM8fTwktrtDDyAQOo/Team2?type=design&node-id=0%3A1&mode=design&t=mt0TesocXqp5YVeN-1)에서 확인할 수 있듯이, User 생성 시 `id`과 `email`은 입력받고 있지 않으므로 이 필드는 지워주시면 좋을 것 같습니다

2023-10-15 04:22 UTC, thisisWooyeol commented on springboot/src/main/kotlin/com/goliath/emojihub/springboot/dto/SignUpRequest.kt
> +    var password: String,
추후 확장성을 위해 `email` 은 남겨두고 `id` 삭제 후 다시 push했습니다! 리뷰 부탁드려요

2023-10-15 04:27 UTC, thisisWooyeol approved these changes

2023-10-15 04:27 UTC, thisisWooyeol commented on springboot/src/main/kotlin/com/goliath/emojihub/springboot/dao/UserDao.kt
> +    }
id 필드 삭제 후, username으로 document(문서) 네이밍하도록 수정.

2023-10-15 04:27 UTC, thisisWooyeol commented on springboot/src/main/kotlin/com/goliath/emojihub/springboot/dto/UserDto.kt
> +) {
`UserDto`에 id 삭제 리뷰 반영

2023-10-15 12:43 UTC, peng-u-0807 commented on springboot/src/main/kotlin/com/goliath/emojihub/springboot/dao/UserDao.kt
> +    }
`!!` 연산자 사용의 지양 + Early return pattern + `UserServiceImpl`에서 null에 대한 처리가 이루어짐을 감안하여 다음과 같이 작성하는건 어떨지 제안 드려봅니다 😀 굳이? 싶다면 넘겨도 괜찮습니다
```suggestion
    fun getUser(username: String): UserDto? {
        val db: Firestore = FirestoreClient.getFirestore()
        val future = db.collection(COLLECTION_NAME).document(username).get()
        val document: DocumentSnapshot = future.get()
        if (document.exists()) {
            return document.toObject(UserDto::class.java)
        }
        return null
    }
```

2023-10-15 12:46 UTC, peng-u-0807 approved these changes

2023-10-15 12:55 UTC, thisisWooyeol commented on springboot/src/main/kotlin/com/goliath/emojihub/springboot/dao/UserDao.kt
> +    }
반영해 푸시하겠습니다 :+1:

2023-10-15 13:01 UTC, merged